name: steap
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - adjusttext=0.7.3.1=py_1
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.7.4=py39h3811e60_0
  - alabaster=0.7.12=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcrypt=3.2.0=py39h3811e60_1
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bioservices=1.7.11=pyh3252c3a_0
  - biothings_client=0.2.5=pyh3252c3a_0
  - blosc=1.21.0=h9c3ff4c_0
  - boto3=1.17.19=pyhd8ed1ab_0
  - botocore=1.20.19=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - cairo=1.16.0=h7979940_1007
  - certifi=2020.12.5=py39hf3d152e_1
  - cffi=1.14.5=py39he32792d_0
  - chardet=4.0.0=py39hf3d152e_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=4.7.2=py39hf3d152e_0
  - configargparse=1.3=pyhd8ed1ab_0
  - cryptography=3.4.4=py39h95dcef6_0
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py39h07f9747_1
  - dbus=1.13.6=hfdff14a_1
  - decorator=4.4.2=py_0
  - docutils=0.16=py39hf3d152e_3
  - dropbox=10.9.0=pyhd3deb0d_0
  - easydev=0.10.1=pyh9f0ad1d_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=h9c3ff4c_0
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1004
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=5.0.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.2=h0c95a7a_2
  - gettext=0.19.8.1=h0b5b191_1005
  - gevent=21.1.2=py39h3811e60_0
  - giflib=5.2.1=h36c2ea0_2
  - git-lfs=2.13.2=ha770c72_0
  - gitdb=4.0.5=pyhd8ed1ab_1
  - gitpython=3.1.14=pyhd8ed1ab_0
  - glib=2.66.7=h9c3ff4c_1
  - glib-tools=2.66.7=h9c3ff4c_1
  - google-api-core=1.25.1=pyh44b312d_0
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-cloud-core=1.5.0=pyhd3deb0d_0
  - google-cloud-storage=1.35.0=pyhd3deb0d_0
  - google-crc32c=1.1.2=py39hb81f231_0
  - google-resumable-media=1.2.0=pyhd3deb0d_0
  - googleapis-common-protos=1.52.0=py39hf3d152e_1
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.46.1=h93c640b_4
  - greenlet=0.4.17=py39h3811e60_2
  - grequests=0.6.0=pyh9f0ad1d_0
  - grpcio=1.36.0=py39hff7568b_0
  - gst-plugins-base=1.18.3=h04508c2_0
  - gstreamer=1.18.3=h3560a44_0
  - gtk2=2.24.33=hab0c2f8_0
  - gts=0.7.6=h64030ff_2
  - harfbuzz=2.7.4=h5cf4720_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=3.7.0=py39hf3d152e_0
  - importlib_metadata=3.7.0=hd8ed1ab_0
  - ipykernel=5.5.0=py39hef51801_1
  - ipython=7.21.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py39hf3d152e_2
  - jinja2=2.11.3=pyh44b312d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py39hf3d152e_0
  - kiwisolver=1.3.1=py39h1a9c180_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.0.1=default_ha53f305_1
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libcurl=7.75.0=hc4aaa36_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgd=2.3.0=h47910db_1
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.66.7=h3e27bee_1
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm11=11.0.1=hf817b99_0
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - libprotobuf=3.15.3=h780b84a_0
  - librsvg=2.50.3=hfa39831_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libtool=2.4.6=h58526e2_1007
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.41.0=h7f98852_0
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.10=h72842e0_3
  - libxslt=1.1.33=h15afd5d_2
  - lxml=4.6.2=py39h107f48f_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - markupsafe=1.1.1=py39h3811e60_3
  - matplotlib=3.3.4=py39hf3d152e_0
  - matplotlib-base=3.3.4=py39h2fa2bec_0
  - matplotlib-venn=0.11.6=pyh9f0ad1d_0
  - mock=4.0.3=py39hf3d152e_1
  - multidict=5.1.0=py39h3811e60_1
  - mygene=3.2.1=pyh3252c3a_0
  - mysql-common=8.0.23=ha770c72_1
  - mysql-libs=8.0.23=h935591d_1
  - ncurses=6.2=h58526e2_4
  - networkx=2.5=py_0
  - nspr=4.29=h9c3ff4c_1
  - nss=3.62=hb5efdd6_0
  - numexpr=2.7.3=py39hde0f152_0
  - numpy=1.20.1=py39hdbf815f_0
  - numpydoc=1.1.0=py_1
  - olefile=0.46=pyh9f0ad1d_1
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1j=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py39hde0f152_0
  - pango=1.42.4=h69149e4_5
  - paramiko=2.7.2=pyh9f0ad1d_0
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.1=py39hf95b381_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - protobuf=3.15.3=py39he80948d_0
  - psutil=5.8.0=py39h3811e60_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py39h78163bd_0
  - pynacl=1.4.0=py39h3811e60_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hf3d152e_7
  - pyqt-impl=5.12.3=py39h0fcd23e_7
  - pyqt5-sip=4.19.18=py39he80948d_7
  - pyqtchart=5.12=py39h0fcd23e_7
  - pyqtwebengine=5.12.1=py39h0fcd23e_7
  - pyrsistent=0.17.3=py39h3811e60_2
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py39hf3d152e_3
  - pytables=3.6.1=py39hf6dc253_3
  - python=3.9.2=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.6=pyhd8ed1ab_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - pyzmq=22.0.3=py39h37b5a0c_1
  - qt=5.12.9=hda022c4_4
  - ratelimiter=1.2.0=py_1002
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - requests-cache=0.5.0=py_0
  - rsa=4.7.2=pyh44b312d_0
  - s3transfer=0.3.4=pyhd8ed1ab_0
  - scipy=1.6.0=py39hee8e79c_0
  - setuptools=49.6.0=py39hf3d152e_3
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=5.4.5=0
  - snakemake-minimal=5.4.5=py_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - soupsieve=2.0.1=py_1
  - sphinx=3.5.1=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.34.0=h74cdb3f_0
  - statsmodels=0.12.2=py39hce5d2b2_0
  - suds-jurko=0.6=py39hf3d152e_1005
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - upsetplot=0.4.1=pyh9f0ad1d_1
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py39h3811e60_3
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.5.1=py39h07f9747_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zope.event=4.5.0=pyh9f0ad1d_0
  - zope.interface=5.2.0=py39h3811e60_1
  - zstd=1.4.8=ha95c52a_1
  - pip:
    - gseapy==0.10.4
    - xmltodict==0.12.0
